# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DNSPageStyle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DNSPageView', '~> 1.1.1'
  # Pods for DNSPageStyle

end
