# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameplay' do
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  use_frameworks!
#  pod 'BHBPopView'
  # Pods for gameplay
  pod 'Kingfisher'
  pod 'MBProgressHUD'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'GTMRefresh', '~> 1.3.4'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'ReachabilitySwift'
  pod 'SkeletonView'
  pod 'SnapKit'
  pod 'SwiftTheme'
end
