# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YiboGameIos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 4.6.1'
  pod 'MBProgressHUD'
  pod 'Alamofire'
  pod 'HandyJSON', '~> 4.1.0'
#  pod 'MJRefresh'
  pod 'MJRefresh', '~> 3.1.14.1'
  pod 'ReachabilitySwift'
  pod 'SnapKit'                   # AutoLayout
#  pod "EFAutoScrollLabel", '~> 1.0.0'
  pod 'GTMRefresh', '<= 1.3.4'
  pod 'DNSPageView', '~> 1.1.1'

#  pod 'BHBPopView'
  # Pods for YiboGameIos

  target 'YiboGameIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
