# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DemoSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for DemoSwift
  pod 'Alamofire', '~> 4.7.0'
  pod 'HandyJSON', '~> 5.0.0-beta'
  pod 'SnapKit', '~> 4.2.0'
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'YYModel', '~> 1.0.4'
end
