# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Koala' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Koala
  pod 'AFNetworking', '3.2.1'
  pod 'Masonry', '1.1.0'
  pod 'YYModel', '1.0.4'
  
  pod 'UMCCommon', '2.0.1'
  pod 'UMCSecurityPlugins', '1.0.6'
  pod 'UMCAnalytics', '6.0.3' # 统计
  pod 'UMCPush', '3.2.4' # push
  
end
