# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ColorWheel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ColorWheel
  #hide
  pod 'Masonry', '1.1.0'
  pod 'HandyJSON', '5.0.0-beta.1'
  pod 'Alamofire', '4.8.0'
  
  #umeng
  pod 'UMCCommon', '~> 2.0.1'
  pod 'UMCSecurityPlugins', '~> 1.0.6'
  pod 'UMCAnalytics', '~> 6.0.3' # 统计
  pod 'UMCPush', '~> 3.2.4' # push

end
